FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# books

架空の書店向けのAPIの定義です。
※Apiaryを利用したモックを想定しています。

## Group Books

書籍に関するAPIです。CRUD操作を実装します。

## Book [/books/{book_id}.json]

書籍オブジェクトは以下の属性を持ちます。

+ id - 本のID
+ title - 本のタイトル
+ author_id - 著者のID
+ created_at - 作成日(ISO8601形式)
+ updated_at - 更新日(ISO8601形式)

+ Parameters
    + book_id: 4 (required, number) - 本のID

### 書籍を取得する。 [GET]

+ Response 200 (application/json)

        {
            "id": 4,
            "title": "Conversation With God",
            "author_id": 2,
            "created_at": "2015-06-10T06:15:50.479Z",
            "updated_at": "2015-06-10T06:15:50.479Z"
        }

### 書籍を更新する。 [PUT]

+ Response 200 (application/json)

        {
            "id": 4,
            "title": "Conversation With God",
            "author_id": 2,
            "created_at": "2015-06-10T06:15:50.479Z",
            "updated_at": "2015-06-10T06:15:50.479Z"
        }

### 書籍を削除する。 [DELETE]

+ Response 200 (application/json)

        {
            "id": 4,
            "title": "Conversation With God",
            "author_id": 2,
            "created_at": "2015-06-10T06:15:50.479Z",
            "updated_at": "2015-06-10T06:15:50.479Z"
        }

## Books Collection [/books.json]

### 書籍の一覧 [GET]

+ Response 200 (application/json)

        [
          {
            "id": 4,
            "title": "Conversation With God",
            "author_id": 2,
            "created_at": "2015-06-10T06:15:50.479Z",
            "updated_at": "2015-06-10T06:15:50.479Z"
          },
          {
            "id": 5,
            "title": "Home with God",
            "author_id": 2,
            "created_at": "2015-06-10T06:15:50.481Z",
            "updated_at": "2015-06-10T06:15:50.481Z"
          }
        ]

### 書籍の作成 [POST]

このアクションを利用する事で、書籍を作成する事ができます。
書籍の情報が含まれたJSONデータを要求します。

+ book (string) - 書籍のJSONデータ

+ Request (application/json)

        {
            "title": "Parallel Computing",
            "author_id": 3
        }

+ Response 201 (application/json)

        {
           "id": 10,
           "title": "Parallel Computing",
           "author_id": 3,
           "created_at": "2015-06-10T06:15:50.479Z",
           "updated_at": "2015-06-10T06:15:50.479Z"
        }

## Group Authors

著者に関するAPIです。一覧操作のみをサポートします。

## Author [/authors/{author_id}.json]

著者オブジェクトは以下の属性を持ちます。

+ id - 著者のID
+ name - 著者の氏名(フルネーム)
+ created_at - 作成日(ISO8601形式)
+ updated_at - 更新日(ISO8601形式)

+ Parameters
    + author_id: 4 (required, number) - 著者のID

## Authors Collection [/authors.json]

### 書籍の一覧 [GET]

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "name": "Stephen King",
            "created_at": "2015-06-10T06:15:50.420Z",
            "updated_at": "2015-06-10T06:15:50.420Z"
          },
          {
            "id": 2,
            "name": "Neale Donald Walsch",
            "created_at": "2015-06-10T06:15:50.423Z",
            "updated_at": "2015-06-10T06:15:50.423Z"
          }
        ]

## Group Shops

書店に関するAPIです。一覧操作のみをサポートします。

## Shop [/shops/{shop_id}.json]

書店オブジェクトは以下の属性を持ちます。

+ id - 書店のID
+ name - 書店名
+ created_at - 作成日(ISO8601形式)
+ updated_at - 更新日(ISO8601形式)

+ Parameters
    + shop_id: 4 (required, number) - 書店のID

## Shops Collection [/shops.json]

### 書店の一覧 [GET]

+ Response 200 (application/json)

        [
          {
            "id": 1,
            "name": "Shinjuku Nishiguchi",
            "created_at": "2015-06-10T06:15:50.440Z",
            "updated_at": "2015-06-10T06:15:50.440Z"
          },
          {
            "id": 2,
            "name": "Ikebukuro",
            "created_at": "2015-06-10T06:15:50.443Z",
            "updated_at": "2015-06-10T06:15:50.443Z"
          }
        ]
